import type { DistanceModel, ImpulseType, PannerModel, RoomSize, SpaceType, SurfaceMaterial } from '@common/types'
import type { ResponseFormat } from '../../../../clients/groq/generate-structured-output.client'

export default {
	type: 'json_schema',
	json_schema: {
		name: 'spatial_audio_config',
		strict: true,
		schema: {
			type: 'object',
			properties: {
				spatial_config: {
					type: 'object',
					properties: {
						listener_position: {
							type: 'object',
							properties: {
								x: { type: 'number' },
								y: { type: 'number' },
								z: { type: 'number' },
							},
							required: ['x', 'y', 'z'],
							additionalProperties: false,
						},
						source_position: {
							type: 'object',
							properties: {
								x: { type: 'number' },
								y: { type: 'number' },
								z: { type: 'number' },
							},
							required: ['x', 'y', 'z'],
							additionalProperties: false,
						},
						distance_meters: { type: 'number' },
						azimuth_degrees: { type: 'number' },
						elevation_degrees: { type: 'number' },
						panner_model: {
							type: 'string',
							enum: ['equalpower', 'HRTF'] satisfies PannerModel[],
						},
						distance_model: {
							type: 'string',
							enum: ['linear', 'inverse', 'exponential'] satisfies DistanceModel[],
						},
						ref_distance: { type: 'number' },
						rolloff_factor: { type: 'number' },
						max_distance: { type: 'number' },
					},
					required: [
						'listener_position',
						'source_position',
						'distance_meters',
						'azimuth_degrees',
						'elevation_degrees',
						'panner_model',
						'distance_model',
						'ref_distance',
						'rolloff_factor',
						'max_distance',
					],
					additionalProperties: false,
				},
				acoustic_space: {
					type: 'object',
					properties: {
						space_type: {
							type: 'string',
							enum: [
								'cathedral',
								'concert_hall',
								'cave',
								'tunnel',
								'hallway',
								'forest',
								'amphitheater',
								'small_room',
								'large_room',
								'distant_room',
								'outdoor',
								'studio',
								'church',
								'bathroom',
								'garage',
								'arena',
							] satisfies SpaceType[],
						},
						reverb_time_rt60: { type: 'number' },
						damping_factor: { type: 'number' },
						early_reflections_delay_ms: { type: 'number' },
						room_size_category: {
							type: 'string',
							enum: ['tiny', 'small', 'medium', 'large', 'huge'] satisfies RoomSize[],
						},
						surface_material: {
							type: 'string',
							enum: [
								'marble',
								'concrete',
								'wood',
								'brick',
								'glass',
								'carpet',
								'tile',
								'metal',
								'fabric',
								'stone',
								'plaster',
								'grass',
								'dirt',
								'water',
								'sand',
							] satisfies SurfaceMaterial[],
						},
						impulse_response_type: {
							type: 'string',
							enum: ['synthetic', 'recorded', 'hybrid', 'procedural', 'none'] satisfies ImpulseType[],
						},
					},
					required: [
						'space_type',
						'reverb_time_rt60',
						'damping_factor',
						'early_reflections_delay_ms',
						'room_size_category',
						'surface_material',
						'impulse_response_type',
					],
					additionalProperties: false,
				},
				audio_processing: {
					type: 'object',
					properties: {
						dry_wet_mix: { type: 'number' },
						high_frequency_damping: { type: 'number' },
						low_cut_frequency_hz: { type: 'number' },
						high_cut_frequency_hz: { type: 'number' },
						air_absorption_enabled: { type: 'boolean' },
						air_absorption_db_per_meter: { type: 'number' },
						occlusion_factor: { type: 'number' },
						compression_threshold_db: { type: 'number' },
						compression_ratio: { type: 'number' },
					},
					required: [
						'dry_wet_mix',
						'high_frequency_damping',
						'low_cut_frequency_hz',
						'high_cut_frequency_hz',
						'air_absorption_enabled',
						'air_absorption_db_per_meter',
						'occlusion_factor',
						'compression_threshold_db',
						'compression_ratio',
					],
					additionalProperties: false,
				},
			},
			required: ['spatial_config', 'acoustic_space', 'audio_processing'],
			additionalProperties: false,
		},
	},
} as const satisfies ResponseFormat
